import XCTest
@testable import Bull

/// Both fixtures here were generated by constructing real `DEFAULT_ITEMS` /
/// `DEFAULT_SETTINGS` values in the actual JS environment and serialising them
/// exactly as app.js's own export button does — not hand-typed JSON — so a
/// pass means the importer handles the real shape, including a legacy rule
/// format app.js itself still tolerates on read.
final class DataImportTests: XCTestCase {

    func loadFixture(_ name: String) -> Data {
        let url = Bundle(for: DataImportTests.self).url(forResource: name, withExtension: "json")!
        return try! Data(contentsOf: url)
    }

    // MARK: - Clean fixture: exact-value parity

    func testCleanFixtureDecodesExactly() throws {
        let data = loadFixture("BackupFixture")
        let bull = try JSONDecoder().decode(BullData.self, from: data)

        XCTAssertEqual(bull.version, 7)
        XCTAssertEqual(bull.items.count, 21) // 20 defaults + 1 custom
        XCTAssertTrue(bull.items.contains { $0.label == "Late Night Phone In Bed" })
        XCTAssertEqual(bull.days.count, 4)
        XCTAssertEqual(bull.days["2026-08-10"]?.access, .med)
        XCTAssertEqual(bull.days["2026-08-10"]?.recovery, 55)
        XCTAssertEqual(bull.days["2026-08-12"]?.sick, true)
        XCTAssertEqual(bull.days["2026-08-13"]?.excluded, true)
        XCTAssertEqual(bull.days["2026-08-13"]?.checkout, .few)

        XCTAssertEqual(bull.urges.count, 2)
        XCTAssertEqual(Set(bull.urges.flatMap(\.triggers)), ["Home Alone, Unstructured Time"])
        XCTAssertTrue(bull.urges.contains { $0.triggers.isEmpty && $0.responses.isEmpty }, "bare 'just the breathing' urge should decode with empty arrays, not fail")

        XCTAssertEqual(bull.relapses.count, 1)
        XCTAssertEqual(bull.relapses.first?.type, .edge)
        XCTAssertEqual(bull.relapses.first?.triggers, ["Junk Food"])

        XCTAssertEqual(bull.wetDreams.count, 1)

        XCTAssertEqual(bull.rules.count, 2)
        // The legacy singular trigger/response fixture entry must decode into
        // the plural array shape, same tolerance app.js itself applies.
        XCTAssertTrue(bull.rules.contains { $0.triggers == ["Junk Food"] && $0.responses == ["Cold water"] },
                      "legacy singular trigger/response shape must decode into arrays")

        XCTAssertEqual(bull.settings.recoveryRiskWeight, .high)
        XCTAssertEqual(bull.settings.sleepWeight, .vhigh)
        XCTAssertNotNil(bull.settings.lastOpenedTs)
        XCTAssertEqual(bull.settings.lastOpenedTs!, 1_786_611_600_000, accuracy: 1) // 2026-08-13T09:00:00Z, verified via node Date.parse
        XCTAssertEqual(bull.firstUse, 1_780_272_000_000, accuracy: 1) // 2026-06-01T00:00:00Z, exact value from the fixture generator
    }

    // MARK: - Sanity: the comparison itself must be able to fail

    func testHarnessDetectsWrongValue() throws {
        let data = loadFixture("BackupFixture")
        let bull = try JSONDecoder().decode(BullData.self, from: data)
        XCTAssertNotEqual(bull.items.count, 999, "sanity: a wrong value must not compare equal")
    }

    // MARK: - Corrupted fixture: exactly one bad element per collection is skipped, never the whole collection

    func testCorruptedFixtureSkipsOnlyBadElements() throws {
        let cleanData = loadFixture("BackupFixture")
        let cleanBull = try JSONDecoder().decode(BullData.self, from: cleanData)

        let corruptedData = loadFixture("BackupFixtureCorrupted")
        guard case .success(let (corruptedBull, report)) = BackupImporter.importBackup(from: corruptedData) else {
            XCTFail("expected corrupted-but-recoverable fixture to import, not fail outright")
            return
        }

        // Every collection should report EXACTLY one skip — proving the
        // failure is isolated per element, not cascading to the collection.
        XCTAssertEqual(report.skipped["items"], 1)
        XCTAssertEqual(report.skipped["urges"], 1)
        XCTAssertEqual(report.skipped["relapses"], 1)
        XCTAssertEqual(report.skipped["wetDreams"], 1)
        XCTAssertEqual(report.skipped["rules"], 1)
        XCTAssertEqual(report.skipped["days"], 1)
        XCTAssertTrue(report.hadSkips)

        // And critically: every VALID element from the clean fixture still
        // made it through, unaffected by its corrupted sibling in the same
        // collection. This is the actual bug this whole file exists to catch
        // — a naive `try? decode([T].self)` would have produced empty
        // collections here instead of "everything but the one bad element".
        XCTAssertEqual(corruptedBull.items.count, cleanBull.items.count)
        XCTAssertEqual(Set(corruptedBull.items.map(\.id)), Set(cleanBull.items.map(\.id)))
        XCTAssertEqual(corruptedBull.urges.count, cleanBull.urges.count)
        XCTAssertEqual(corruptedBull.relapses.count, cleanBull.relapses.count)
        XCTAssertEqual(corruptedBull.wetDreams.count, cleanBull.wetDreams.count)
        XCTAssertEqual(corruptedBull.rules.count, cleanBull.rules.count)
        XCTAssertEqual(corruptedBull.days.count, cleanBull.days.count)
        XCTAssertEqual(Set(corruptedBull.days.keys), Set(cleanBull.days.keys))
    }

    /// Proves the anti-cascade guarantee would actually have caught the naive
    /// bug if it were reintroduced: decoding the SAME corrupted fixture with a
    /// plain `try? container.decode([Item].self, ...)`-style all-or-nothing
    /// approach must produce an EMPTY collection, not a partially-populated
    /// one — establishing that "21 items survived" in the test above is a
    /// real assertion, not a coincidence of Codable's default behaviour.
    func testNaiveAllOrNothingDecodeWouldHaveLostEverything() throws {
        let corruptedData = loadFixture("BackupFixtureCorrupted")
        struct NaiveWrapper: Decodable { let items: [Item] }
        let naive = try? JSONDecoder().decode(NaiveWrapper.self, from: corruptedData)
        XCTAssertNil(naive, "a plain array decode over one bad element should throw entirely — if this ever stops being true, the lenient decoder's value proposition should be re-examined")
    }

    // MARK: - Round-trip

    func testRoundTripPreservesData() throws {
        let data = loadFixture("BackupFixture")
        let original = try JSONDecoder().decode(BullData.self, from: data)
        let reEncoded = try BackupImporter.exportData(original)
        let reDecoded = try JSONDecoder().decode(BullData.self, from: reEncoded)
        XCTAssertEqual(original, reDecoded)

        // Rules re-encode in the CURRENT plural shape even when the source
        // was legacy singular — a second round-trip must be byte-stable.
        let reReEncoded = try BackupImporter.exportData(reDecoded)
        let reReDecoded = try JSONDecoder().decode(BullData.self, from: reReEncoded)
        XCTAssertEqual(reDecoded, reReDecoded)
    }

    // MARK: - Error paths

    func testNotJSONFails() {
        let garbage = Data("this is not json {{{".utf8)
        guard case .failure(let err) = BackupImporter.importBackup(from: garbage) else {
            XCTFail("expected failure"); return
        }
        XCTAssertEqual(err, .notJSON)
    }

    func testValidJSONButNotABackupFails() {
        let notABackup = Data(#"{"hello": "world"}"#.utf8)
        guard case .failure(let err) = BackupImporter.importBackup(from: notABackup) else {
            XCTFail("expected failure"); return
        }
        XCTAssertEqual(err, .notABullBackup)
    }

    func testJSONArrayInsteadOfObjectFails() {
        let arr = Data("[1,2,3]".utf8)
        guard case .failure(let err) = BackupImporter.importBackup(from: arr) else {
            XCTFail("expected failure"); return
        }
        XCTAssertEqual(err, .notABullBackup)
    }

    // MARK: - The empty-items-is-legitimate edge case

    func testGenuinelyEmptyItemsArrayIsRespectedNotReplacedWithDefaults() throws {
        // Simulates a user who deleted every single item through Settings —
        // a real, reachable state (deleteItem has no minimum-count guard).
        let json = """
        {"version":7,"settings":{},"items":[],"days":{},"urges":[],"relapses":[],"wetDreams":[],"rules":[],"firstUse":0}
        """
        let bull = try JSONDecoder().decode(BullData.self, from: Data(json.utf8))
        XCTAssertEqual(bull.items.count, 0, "an intentionally empty item list must not be silently repopulated with defaults")
    }

    func testMissingItemsKeyFallsBackToDefaults() throws {
        // Distinct from the above: here the key is ABSENT, which is the
        // "unreadable/legacy file" case where defaults genuinely make sense.
        let json = """
        {"version":7,"settings":{},"days":{},"urges":[],"relapses":[],"wetDreams":[],"rules":[],"firstUse":0}
        """
        let bull = try JSONDecoder().decode(BullData.self, from: Data(json.utf8))
        XCTAssertEqual(bull.items.count, DefaultItems.all.count)
    }
}
